config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :classrooms
  resources :students
  resources :subjects
  resources :teachers
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :school
  has_many :students, dependent: :destroy
  has_many :teachers, dependent: :destroy
  validates :standard, presence: true
  validates :school_id, presence: true
  validates :no_of_students, presence: true, inclusion: { in: 10..60 }
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @classrooms = Classroom.all
    respond_to do |format|
      format.json { render json: { classrooms: @classrooms }, status: :ok }
      format.html
    end
  end

  def show
    @classroom = Classroom.find(params[:id])
    respond_to do |format|
      format.json { render json: { classroom: @classroom }, status: :ok }
      format.html
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { render html: { error: e.message }, status: :not_found }
    end
  end

  def edit
    @classroom = Classroom.find(params[:id])
  end

  def create
    @classroom = Classroom.new(classroom_params)
    if @classroom.save
      respond_to do |format|
        format.json { render json: { classroom: @classroom }, status: :ok }
        format.html { redirect_to :back }
      end
    else
      respond_to do |format|
        format.json { render json: { error: @classroom.errors }, status: :unprocessable_entity }
        format.html { render html: { error: @classroom.errors.messages }, status: :unprocessable_entity }
      end
    end
  end

  def update
    @classroom = Classroom.find(params[:id])
    if @classroom.update(classroom_params)
      respond_to do |format|
        format.json { render json: { classroom: @classroom }, status: :ok }
        format.html { redirect_to @classroom }
      end
    else
      respond_to do |format|
        format.json { render json: { error: @classroom.errors }, status: :unprocessable_entity }
        format.html { render html: { error: @classroom.errors.messages }, status: :not_found }
      end
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { render html: { error: @classroom.errors.messages }, status: :not_found }
    end
  end

  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy
    respond_to do |format|
      format.json { render json: { message: 'Successfully deleted' }, status: :ok }
      format.html { redirect_to :back }
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { redirect_to @classroom }
    end
  end

  private

  def classroom_params
    params.require(:classroom).permit(:standard, :no_of_students, :school_id)
  end
end

app/views/classrooms/_classroom.html.erb
<p>
  <strong>Standard:</strong>
  <%= classroom.standard %>
</p> 
<p>
  <strong>Classroom:</strong>
  <%= classroom.no_of_students %>
</p>
<p>
  <%= link_to 'Edit Classroom', edit_classroom_path(classroom) %> <br>
  <%= link_to 'Destroy Classroom', classroom, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/classrooms/_form.html.erb
<%= form_for @school.classrooms.build do |form| %>
  <p>
    <%= form.label :standard %><br>
    <%= form.text_field :standard %>
  </p>
  <p>
    <%= form.label :no_of_students %><br>
    <%= form.text_area :no_of_students %>
  </p>
  <%= form.hidden_field :school_id, :value => @school_id %>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/classrooms/edit.html.erb
<%= form_for @classroom do |form| %>
  <p>
    <%= form.label :standard %><br>
    <%= form.text_field :standard %>
  </p>
  <p>
    <%= form.label :no_of_students %><br>
    <%= form.text_area :no_of_students %>
  </p>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>

app/views/classrooms/index.html.erb
<h1>Classrooms:</h1><br>
<table>
  <tr>
    <th>Standard</th>
  </tr>
  <% @classrooms.each do |classroom| %>
    <tr>
      <td><%= classroom.standard %></td>
      <td><%= link_to 'Show', classroom_path(classroom) %></td>
      <td><%= link_to 'Edit Classroom', edit_classroom_path(classroom) %></td>
      <td><%= link_to 'Destroy', classroom_path(classroom), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Home', schools_path %>

app/views/classrooms/show.html.erb
<h2>Classroom:</h2>
<p><%= @classroom.standard %></p>
<p><%= @classroom.no_of_students %></p>

<h2>Students</h2>
<% @classroom.students.each do |student| %>
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p> 
  <p>
    <strong>Address:</strong>
    <%= student.address %>
  </p>
  <p>
    <strong>Phone no:</strong>
    <%= student.phone_no %>
  </p>
  <p>
    <strong>Percentage:</strong>
    <%= student.percentage %>
  </p>
  <p>
    <%= link_to 'Edit student', edit_student_path(student) %> <br>
    <%= link_to 'Destroy student', student, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h2>Add a student:</h2>
<%= form_for @classroom.students.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>
  <p>
    <%= form.label :phone_no %><br>
    <%= form.text_field :phone_no %>
  </p>
  <p>
    <%= form.label :percentage %><br>
    <%= form.text_field :percentage %>
  </p>
  <%= form.hidden_field :classroom_id, :value => @classroom.id %>
  <%= form.hidden_field :school_id, :value => @classroom.school_id %>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>
<br> <%= link_to 'All students', students_path %> <br>

<h2>Teachers</h2>
<% @classroom.teachers.each do |teacher| %>
  <p>
    <strong>Name:</strong>
    <%= teacher.name %>
  </p> 
  <p>
    <strong>Subject Name:</strong>
    <%= teacher.subject_name %>
  </p>
  <p>
    <strong>Salary:</strong>
    <%= teacher.salary %>
  </p>
  <p>
    <%= link_to 'Edit teacher', edit_teacher_path(teacher) %><br>
    <%= link_to 'Destroy teacher', teacher, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h2>Add a teacher:</h2>
<%= form_for @classroom.teachers.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :subject_name %><br>
    <%= form.text_area :subject_name %>
  </p>
  <p>
    <%= form.label :salary %><br>
    <%= form.text_area :salary %>
  </p>
  <%= form.hidden_field :classroom_id, :value => @classroom.id %>
  <%= form.hidden_field :school_id, :value => @classroom.school_id %> 
  <%= form.hidden_field :student_ids, :value => @classroom.student_ids %>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>
<br> <%= link_to 'All teachers', teachers_path %> <br>

<%= link_to 'Edit Classroom', edit_classroom_path(@classroom) %>  |
<%= link_to 'Back', classrooms_path %>