config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :classrooms
  resources :students
  resources :subjects
  resources :teachers
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :classrooms, dependent: :destroy
  has_many :students, dependent: :destroy
  has_many :subjects, dependent: :destroy
  has_many :teachers, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true, length: { in: 8..15 }
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school
  belongs_to :classroom
  has_many :student_subject, dependent: :destroy
  has_many :student_teacher, dependent: :destroy
  has_many :subjects, through: :student_subject, dependent: :destroy
  has_many :teachers, through: :student_teacher, dependent: :destroy
  validates :name, :address, :phone_no, presence: true
  validates :phone_no, length: { in: 8..15 }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @students = Student.all
    respond_to do |format|
      format.json { render json: { students: @students }, status: :ok }
      format.html
    end
  end

  def show
    @student = Student.find(params[:id])
    respond_to do |format|
      format.json { render json: { student: @student }, status: :ok }
      format.html
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { render html: { error: e.message }, status: :not_found }
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      respond_to do |format|
        format.json { render json: { student: @student }, status: :ok }
        format.html { redirect_to :back }
      end
    else
      respond_to do |format|
        format.json { render json: { error: @student.errors }, status: :unprocessable_entity }
        format.html { render html: { message: @student.errors.messages }, status: :unprocessable_entity }
      end
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      respond_to do |format|
        format.json { render json: { student: @student }, status: :ok }
        format.html { redirect_to @student }
      end
    else
      respond_to do |format|
        format.json { render json: { error: @student.errors }, status: :unprocessable_entity }
        format.html { render html: { message: @student.errors.messages }, status: :unprocessable_entity }
      end
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { render html: { message: @student.errors.messages }, status: :not_found }
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    respond_to do |format|
      format.json { render json: { message: 'Successfully deleted' }, status: :ok }
      format.html { redirect_to :back }
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { redirect_to @student }
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :address, :phone_no, :percentage, :school_id, :classroom_id, :subject_ids, :teacher_ids)
  end
end

app/views/students/_form.html.erb
<%= form_for @school.students.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>
  <p>
    <%= form.label :phone_no %><br>
    <%= form.text_field :phone_no %>
  </p>
  <p>
    <%= form.label :percentage %><br>
    <%= form.text_field :percentage %>
  </p>
  <%= form.hidden_field :school_id, :value => @school_id %>
  <%= form.hidden_field :classroom_id, :value => @school.classroom_ids %>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/students/_student.html.erb
<p>
  <strong>Name:</strong>
  <%= student.name %>
</p> 
<p>
  <strong>Address:</strong>
  <%= student.address %>
</p>
<p>
  <strong>Phone no:</strong>
  <%= student.phone_no %>
</p>
<p>
  <strong>Percentage:</strong>
  <%= student.percentage %>
</p>
<p>
  <%= link_to 'Edit student', edit_student_path(student) %>  <br>
  <%= link_to 'Destroy student', student, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/students/edit.html.erb
<%= form_for @student do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>
  <p>
    <%= form.label :phone_no %><br>
    <%= form.text_area :phone_no %>
  </p>
  <p>
    <%= form.label :percentage %><br>
    <%= form.text_area :percentage %>
  </p>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>

app/views/students/index.html.erb
<h1>Students:</h1><br>
<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= link_to 'Show', student_path(student) %></td>
      <td><%= link_to 'Edit student', edit_student_path(student) %></td>  
      <td><%= link_to 'Destroy', student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Home', schools_path %>

app/views/students/show.html.erb
<h2>Student:</h2>
<p><%= @student.name %></p>
<p><%= @student.address %></p>
<p><%= @student.phone_no %></p>
<p><%= @student.percentage %></p>

<h2>Subjects</h2>
<% @student.subjects.each do |subject| %>
  <p>
    <strong>Name:</strong>
    <%= subject.name %>
  </p> 
  <p>
    <strong>Duration:</strong>
    <%= subject.subject_duration %>
  </p>
  <p>
    <%= link_to 'Edit subject', edit_subject_path(subject) %> <br>
    <%= link_to 'Destroy subject', subject, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h2>Add a subject:</h2>
<%= form_for @student.subjects.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :subject_duration %><br>
    <%= form.text_area :subject_duration %>
  </p>
  <%= form.hidden_field :student_ids, :value => @student.id %>
  <%= form.hidden_field :school_id, :value => @student.school_id %>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>
<br> <%= link_to 'All subjects', subjects_path %> <br>

<h2>Teachers</h2>
<% @student.teachers.each do |teacher| %>
  <p>
    <strong>Name:</strong>
    <%= teacher.name %>
  </p> 
  <p>
    <strong>Subject Name:</strong>
    <%= teacher.subject_name %>
  </p>
  <p>
    <strong>Salary:</strong>
    <%= teacher.salary %>
  </p>
  <p>
    <%= link_to 'Edit teacher', edit_teacher_path(teacher) %> <br>
    <%= link_to 'Destroy teacher', teacher, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h2>Add a teacher:</h2>
<%= form_for @student.teachers.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :subject_name %><br>
    <%= form.text_area :subject_name %>
  </p>
  <p>
    <%= form.label :salary %><br>
    <%= form.text_area :salary %>
  </p>
  <%= form.hidden_field :student_ids, :value => @student.id %>
  <%= form.hidden_field :school_id, :value => @student.school_id %>
  <%= form.hidden_field :classroom_id, :value => @student.classroom_id %>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>
<br> <%= link_to 'All teachers', teachers_path %> <br>

<%= link_to 'Edit student', edit_student_path(@student) %>  |
<%= link_to 'Back', students_path %>