config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :classrooms
  resources :students
  resources :subjects
  resources :teachers
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :classrooms, dependent: :destroy
  has_many :students, dependent: :destroy
  has_many :subjects, dependent: :destroy
  has_many :teachers, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true, length: { in: 8..15 }
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :school
  has_many :student_subject, dependent: :destroy
  has_many :students, through: :student_subject, dependent: :destroy
  has_many :teachers, dependent: :destroy
  validates :name, :subject_duration, presence: true
  validates :subject_duration, inclusion: { in: 1..8 }
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @subjects = Subject.all
    respond_to do |format|
      format.json { render json: { subjects: @subjects }, status: :ok }
      format.html
    end
  end

  def show
    @subject = Subject.find(params[:id])
    respond_to do |format|
      format.json { render json: { subject: @subject }, status: :ok }
      format.html
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { render html: { error: e.message }, status: :not_found }
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.create(subject_params)
    if @subject.save
      respond_to do |format|
        format.json { render json: { subject: @subject }, status: :ok }
        format.html { redirect_to :back }
      end
    else
      respond_to do |format|
        format.json { render json: { error: @subject.errors }, status: :unprocessable_entity }
        format.html { render html: { message: @subject.errors.messages }, status: :unprocessable_entity }
      end
    end
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      respond_to do |format|
        format.json { render json: { subject: @subject }, status: :ok }
        format.html { redirect_to @subject }
      end
    else
      respond_to do |format|
        format.json { render json: { error: @subject.errors }, status: :unprocessable_entity }
        format.html { render html: { message: @subject.errors.messages }, status: :unprocessable_entity }
      end
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { render html: { message: @subject.errors.messages }, status: :not_found }
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    respond_to do |format|
      format.json { render json: { message: 'Successfully deleted' }, status: :ok }
      format.html { redirect_to :back }
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { redirect_to @subject }
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :subject_duration, :school_id, :student_ids)
  end
end

app/views/subjects/_form.html.erb
<%= form_for @school.subjects.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :subject_duration %><br>
    <%= form.text_area :subject_duration %>
  </p>

  <%= form.hidden_field :school_id, :value => @school_id %>
  <%= form.hidden_field :classroom_id, :value => @school.classroom_ids %>
  <%= form.hidden_field :student_ids, :value => @school.student_ids %>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/subjects/_subject.html.erb
<p>
  <strong>Name:</strong>
  <%= subject.name %>
</p> 
<p>
  <strong>Subject Duration:</strong>
  <%= subject.subject_duration %>
</p>
<p>
  <%= link_to 'Edit subject', edit_subject_path(subject) %>  <br>
  <%= link_to 'Destroy subject', subject, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/subjects/edit.html.erb
<%= form_for @subject do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :subject_duration %><br>
    <%= form.text_area :subject_duration %>
  </p>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>

app/views/subjects/index.html.erb
<h1>Subjects:</h1><br>
<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.name %></td>
      <td><%= link_to 'Show', subject_path(subject) %></td>
      <td><%= link_to 'Edit subject', edit_subject_path(subject) %></td>  
      <td><%= link_to 'Destroy', subject_path(subject), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Home', schools_path %>

app/views/subjects/show.html.erb
<h2>Subject:</h2>
<p><%= @subject.name %></p>
<p><%= @subject.subject_duration %></p>

<h2>Students</h2>
<% @subject.students.each do |student| %>
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p> 
  <p>
    <strong>Address:</strong>
    <%= student.address %>
  </p>
  <p>
    <strong>Phone no:</strong>
    <%= student.phone_no %>
  </p>
  <p>
    <strong>Percentage:</strong>
    <%= student.percentage %>
  </p>
  <p>
    <%= link_to 'Edit student', edit_student_path(student) %><br>
    <%= link_to 'Destroy student', student, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h2>Add a student:</h2>
<%= form_for @subject.students.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>
  <p>
    <%= form.label :phone_no %><br>
    <%= form.text_area :phone_no %>
  </p>
  <p>
    <%= form.label :percentage %><br>
    <%= form.text_area :percentage %>
  </p>
  <%= form.hidden_field :subject_ids, :value => @subject.id %>
  <%= form.hidden_field :school_id, :value => @subject.school_id %>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>
<br> <%= link_to 'All students', students_path %> <br>

<h2>Teachers</h2>
<% @subject.teachers.each do |teacher| %>
  <p>
    <strong>Name:</strong>
    <%= teacher.name %>
  </p> 
  <p>
    <strong>Subject Name:</strong>
    <%= teacher.subject_name %>
  </p>
  <p>
    <strong>Salary:</strong>
    <%= teacher.salary %>
  </p>
  <p>
    <%= link_to 'Edit teacher', edit_teacher_path(teacher) %> <br>
    <%= link_to 'Destroy teacher', teacher, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h2>Add a teacher:</h2>
<%= form_for @subject.teachers.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :subject_name %><br>
    <%= form.text_area :subject_name %>
  </p>
  <p>
    <%= form.label :salary %><br>
    <%= form.text_area :salary %>
  </p>
  <%= form.hidden_field :subject_id, :value => @subject.id %>
  <%= form.hidden_field :school_id, :value => @subject.school_id %>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>
<br> <%= link_to 'All teachers', teachers_path %> <br>

<%= link_to 'Edit subject', edit_subject_path(@subject) %>  |
<%= link_to 'Back', subjects_path %>