config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :classrooms
  resources :students
  resources :subjects
  resources :teachers
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :classrooms, dependent: :destroy
  has_many :students, dependent: :destroy
  has_many :subjects, dependent: :destroy
  has_many :teachers, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true, length: { in: 8..15 }
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school
  belongs_to :classroom
  belongs_to :subject
  has_many :student_teacher, dependent: :destroy
  has_many :students, through: :student_teacher, dependent: :destroy
  validates :name, :subject_name, presence: true
  validates :salary, inclusion: { in: 10_000..90_000 }
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @teachers = Teacher.all
    respond_to do |format|
      format.json { render json: { teachers: @teachers }, status: :ok }
      format.html
    end
  end

  def show
    @teacher = Teacher.find(params[:id])
    respond_to do |format|
      format.json { render json: { teacher: @teacher }, status: :ok }
      format.html
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { render html: { error: e.message }, status: :not_found }
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def create
    @teacher = Teacher.create(teacher_params)
    if @teacher.save
      respond_to do |format|
        format.json { render json: { teacher: @teacher }, status: :ok }
        format.html { redirect_to :back }
      end
    else
      respond_to do |format|
        format.json { render json: { error: @teacher.errors }, status: :unprocessable_entity }
        format.html { render html: { message: @teacher.errors.messages }, status: :unprocessable_entity }
      end
    end
  end

  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.update(teacher_params)
      respond_to do |format|
        format.json { render json: { teacher: @teacher }, status: :ok }
        format.html { redirect_to @teacher }
      end
    else
      respond_to do |format|
        format.json { render json: { error: @teacher.errors }, status: :unprocessable_entity }
        format.html { render html: { message: @teacher.errors.messages }, status: :unprocessable_entity }
      end
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { render html: { message: @teacher.errors.messages }, status: :unprocessable_entity }
    end
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    respond_to do |format|
      format.json { render json: { message: 'Successfully deleted' }, status: :ok }
      format.html { redirect_to :back }
    end
  rescue StandardError => e
    respond_to do |format|
      format.json { render json: { error: e.message }, status: :not_found }
      format.html { redirect_to @teacher }
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:name, :subject_name, :salary, :school_id, :classroom_id, :subject_id, :student_ids)
  end
end

app/views/teachers/_form.html.erb
<%= form_for @school.teachers.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :subject_name %><br>
    <%= form.text_area :subject_name %>
  </p>
  <p>
    <%= form.label :salary %><br>
    <%= form.text_area :salary %>
  </p>
  <%= form.hidden_field :school_id, :value => @school_id %>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/teachers/_teacher.html.erb
<p>
  <strong>Name:</strong>
  <%= teacher.name %>
</p> 
<p>
  <strong>teacher Name:</strong>
  <%= teacher.subject_name %>
</p>
<p>
  <strong>Salary:</strong>
  <%= teacher.salary %>
</p>
<p>
  <%= link_to 'Edit teacher', edit_teacher_path(teacher) %>  <br>
  <%= link_to 'Destroy teacher', teacher, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/teachers/edit.html.erb
<%= form_for @teacher do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :subject_name %><br>
    <%= form.text_area :subject_name %>
  </p>
  <p>
    <%= form.label :salary %><br>
    <%= form.text_area :salary %>
  </p>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>

app/views/teachers/index.html.erb
<h1>Teachers:</h1><br>
<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @teachers.each do |teacher| %>
    <tr>
      <td><%= teacher.name %></td>
      <td><%= link_to 'Show', teacher_path(teacher) %></td>
      <td><%= link_to 'Edit teacher', edit_teacher_path(teacher) %></td>  
      <td><%= link_to 'Destroy', teacher_path(teacher), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Home', schools_path %>

app/views/teachers/show.html.erb
<h2>Teacher:</h2>
<p><%= @teacher.name %></p>
<p><%= @teacher.subject_name %></p>
<p><%= @teacher.salary %></p>

<h2>Students</h2>
<% @teacher.students.each do |student| %>
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p> 
  <p>
    <strong>Address:</strong>
    <%= student.address %>
  </p>
  <p>
    <strong>Phone no:</strong>
    <%= student.phone_no %>
  </p>
  <p>
    <strong>Percentage:</strong>
    <%= student.percentage %>
  </p>
  <p>
    <%= link_to 'Edit student', edit_student_path(student) %> <br>
    <%= link_to 'Destroy student', student, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h2>Add a student:</h2>
<%= form_for @teacher.students.build do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>
  <p>
    <%= form.label :phone_no %><br>
    <%= form.text_area :phone_no %>
  </p>
  <p>
    <%= form.label :percentage %><br>
    <%= form.text_area :percentage %>
  </p>
  <%= form.hidden_field :teacher_ids, :value => @teacher.id %>
  <%= form.hidden_field :school_id, :value => @teacher.school_id %>
  <%= form.hidden_field :student_ids, :value => @teacher.student_ids %>
  <p>
    <%= form.submit "Add" %>
  </p>
<% end %>
<br> <%= link_to 'All students', students_path %> <br>

<%= link_to 'Edit teacher', edit_teacher_path(@teacher) %>  |
<%= link_to 'Back', teachers_path %>